# Generated by Django 3.2.18 on 2023-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonBird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.CharField(blank=True, max_length=255, null=True)),
                ('de', models.CharField(blank=True, max_length=255, null=True)),
                ('fr', models.CharField(blank=True, max_length=255, null=True)),
                ('es', models.CharField(blank=True, max_length=255, null=True)),
                ('pt', models.CharField(blank=True, max_length=255, null=True)),
                ('en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'non_bird',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=255, null=True)),
                ('it', models.CharField(blank=True, max_length=255, null=True)),
                ('de', models.CharField(blank=True, max_length=255, null=True)),
                ('fr', models.CharField(blank=True, max_length=255, null=True)),
                ('es', models.CharField(blank=True, max_length=255, null=True)),
                ('pt', models.CharField(blank=True, max_length=255, null=True)),
                ('en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
    ]
