# Generated by Django 3.2.18 on 2023-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMeasurement',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('remote_id', models.BigIntegerField(blank=True, db_column='REMOTE_ID', null=True)),
                ('ambient_temperature', models.DecimalField(db_column='AMBIENT_TEMPERATURE', decimal_places=2, max_digits=6)),
                ('air_pressure', models.DecimalField(db_column='AIR_PRESSURE', decimal_places=2, max_digits=6)),
                ('humidity', models.DecimalField(db_column='HUMIDITY', decimal_places=2, max_digits=6)),
                ('wind_direction', models.DecimalField(blank=True, db_column='WIND_DIRECTION', decimal_places=2, max_digits=6, null=True)),
                ('direction_variance', models.DecimalField(db_column='DIRECTION_VARIANCE', decimal_places=3, max_digits=3)),
                ('wind_speed', models.DecimalField(db_column='WIND_SPEED', decimal_places=2, max_digits=6)),
                ('wind_gust_speed', models.DecimalField(db_column='WIND_GUST_SPEED', decimal_places=2, max_digits=6)),
                ('rainfall', models.DecimalField(db_column='RAINFALL', decimal_places=2, max_digits=6)),
                ('cpu_temp', models.DecimalField(db_column='CPU_TEMP', decimal_places=1, max_digits=6)),
                ('created', models.DateTimeField(db_column='CREATED')),
            ],
            options={
                'db_table': 'WEATHER_MEASUREMENT',
                'managed': False,
            },
        ),
    ]
